name: ci-vscode

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ci:
    name: Build and test project
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04]
        node-version: [14]
        working-directory: [./vscode]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2.3.4
    
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        working-directory: ${{ matrix.working-directory }}
        run: yarn install

      - name: Lint project
        working-directory: ${{ matrix.working-directory }}
        run: yarn lint

      - name: Test project
        working-directory: ${{ matrix.working-directory }}
        run: yarn test
